# Generated by Django 2.2.7 on 2019-12-13 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=200)),
                ('rooms', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('vacancy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('lpassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetaile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('enroll_no', models.CharField(max_length=100, unique=True)),
                ('course', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=100)),
                ('add_yr', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('gender', models.CharField(max_length=13)),
                ('hostel_name', models.CharField(max_length=200)),
                ('room_no', models.IntegerField()),
                ('mess_dev', models.BooleanField(default=0)),
                ('h_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.HostelDetail')),
            ],
        ),
    ]
